name 'deanwilson-liquidtemplates'
version '0.0.1'
source 'git://github.com/deanwilson/puppet-liquidtemplates.git'
author 'deanwilson'
license 'Apache 2.0'
summary 'Puppet function for processing Liquid Templates'
description 'Puppet function for processing Liquid Templates'
project_page 'https://github.com/deanwilson/puppet-liquidtemplates.git'
